### PR TITLE
Makefile revamp

### PR DESCRIPTION
**Pull request by sthomen**
As promised, the makefile revamp. Includes bonus fix for building on netbsd.

This pull request should probably not be merged, since it removes the "automatic" configure feature and win32 build support.

The install target is also missing, but adding it should be trivial.

### CODE REVIEW

**Comment by uhlin** [comment]
Committed the new build system now but I still kept the old which might be removed later. Does it build on NetBSD now with the new approach if you run ./configure first, in order to create the unix_def.mk file? Else perhaps a NetBSD specific target should be added to the configure script. By now it produces the same unix_def.mk for all the BSDs, i.e. FreeBSD, NetBSD and OpenBSD.

**Comment by sthomen** [comment]
I tried doing a build, and the source is fine, but I had to modify the unix_def.mk somewhat, CFLAGS needs -I/usr/pkg/include -I/usr/pkg/include/ncurses -I/usr/pkg/include/ncursesw and LDFLAGS needs -Wl,-rpath,/usr/pkg/lib -L/usr/pkg/lib and LDLIBS needs to be changed, -lpanelw should be -lgnupanel (this is for ncurses and ncursesw from pkgsrc).

In general, netbsd users are used to this so I don't know if there's any greater need to change much.

Alternatively, you could use the ncurses-config commands to get the platform arguments.

**Comment by uhlin** [comment]
Added a NetBSD specific target now. Does it build now without modifying the file produced by the configure script? A bit unsure because I sorted all the flags with Emacs... hopefully it shouldn't matter. :)

**Comment by sthomen** [comment]
Yup, works perfectly.

**Comment by uhlin** [comment]
Alright. Closing.

**Pull request closed without merging**
